# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-06 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutumnTune', '0003_userdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='mname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
